# _config.yml
title: "Notes from a Working Engineer"
description: "Notes, experiments, and systems—from engineering and ML/LLM to organization, process, and life in motion."
url: "https://flyhigher48.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Change the skin here to try different accents:
# Options: air (clean), aqua (blue), contrast (bold), dark, dirt, focus, mint, neon, plum, sunrise
minimal_mistakes_skin: "air"

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

author:
  name: "Hiren"
  avatar: "/assets/images/avatar.svg"
  bio: "Mechanical engineer (MEng) doing modeling & simulation. I build high‑fidelity FEA, write Python for data, and tinker with ML + LLMs to make engineering calmer and clearer."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/flyhigher48"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: "single"
      author_profile: true
      read_time: true
      share: true
      related: true
      image: "/assets/images/social/default.png"   # ← default social card for posts

collections:
  pages:
    output: true
    permalink: /:name/

markdown: kramdown
highlighter: rouge
exclude:
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor"
  - ".github"
  - "_site"
